basetemplate/MVCBase/Models/Container/ContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBase.Models.Container
{
    public class ContainerViewModel
    {
        public int gkey { get; set; }
        public string equipmentNbr { get; set; }
        public string typeIso { get; set; }
        public string own { get; set; }
        public string typeLength { get; set; }
        public int tareWt { get; set; }
        public int safeWt { get; set; }
    }
}

basetemplate/MVCBase/Controllers/ContainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBase.Controllers
{
    public class ContainerController : Controller
    {
        [HttpGet]
        public ActionResult Index2()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CrearContacto()
        {
            return PartialView(new CrearContactoViewModel());
        }
        [HttpPost]
        public ActionResult CrearContacto(CrearContactoViewModel modelo)
        {
            return Json(new { ok = true });
        }

        // GET: Container
        public ActionResult Index()
        {
            return View(new ContainerController());
        }

        // GET: Container/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Container/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Container/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Container/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Container/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Container/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Container/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public class CrearContactoViewModel
        {
            public string NombreContacto { get; set; }
            public string Direccion { get; set; }
        }
    }
}

basetemplate/MVCBase/Views/Container/CrearContacto.cshtml
@model MVCBase.Controllers.ContainerController.CrearContactoViewModel

@using (Html.BeginForm("CrearContacto", "Container", FormMethod.Post, new { @id = "formCrearContacto" }))
{
    <div class="jarviswidget">
        <header>
            <h2><strong>Test</strong></h2>
        </header>
        <div class="widget-body">
            <div class="form-group col-lg-12">
                @Html.LabelFor(x => x.NombreContacto, new { @class = "col-lg-4" })
                <div class="col-lg-8">
                    @Html.EditorFor(x => x.NombreContacto, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group col-lg-12">
                @Html.LabelFor(x => x.Direccion, new { @class = "col-lg-4" })
                <div class="col-lg-8">
                    @Html.EditorFor(x => x.Direccion, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-success">Mandar Contacto</button>
            </div>
        </div>
    </div>
}



<script>
    $("#formCrearContacto").on('submit', function () {
        $.ajax({
            url: '@Url.Action("CrearContacto", "Container")',
            data: $("#formCrearContacto").serialize(),
            type:"POST",
            success: function (data) {
                if (data.ok = true)
                {
                    Alert("Todo Bien");
                }
               
            }
        });
    });
</script>

basetemplate/MVCBase/Views/Container/Index.cshtml
@model IEnumerable<MVCBase.Models.Container.ContainerViewModel>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.gkey)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.equipmentNbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.typeIso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.own)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.typeLength)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tareWt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.safeWt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.gkey)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.equipmentNbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.typeIso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.own)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.typeLength)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tareWt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.safeWt)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

basetemplate/MVCBase/Views/Container/Index2.cshtml
<h2>Demo</h2>
<button id="btnCargarAjax">Click me</button>
<div id="divCargarAjax">

</div>

<script>
    $("#btnCargarAjax").on('click', function () {
        $.ajax({
            url : '@Url.Action("CrearContacto", "Container")',
            type : "GET",
            success: function (data) {
                $("#divCargarAjax").html(data);
            },
            error : function(data) {

            },
            complete: function (data) {

            }
        });
    });
</script>